backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)
media_folder: "public/images"
public_folder: "/images"
site_url: https://vuosaarenpyorahuolto.fi/
publish_mode: editorial_workflow
# Uncomment local_backend when you need to develop in your local 
local_backend: true # run npx netlify-cms-proxy-server for local testing
collections:
  - name: "pages"
    description: "Sivujen asetukset."
    label: "Sivut"
    editor:
     preview: false
    files:
    - label: "Etusivu"
      name: "home"
      file: "content/home.json"
      preview_path: index
      fields:
        - label: "Herokuva"
          hint: "Herokuva koostuu kuvasta, otsikosta, tekstistä ja toimintakehotteesta. Suosittelen erikseen laittamaan pöytäkoneelle ja mobiilille omat kuvat. Pöytäkoneen herokuvan speksit on suositeltavaa olla 720x1280 ja mobiilin 1000x1000."
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string", required: false}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "image", required: false}
            - { label: "Mobiilin Herokuva", name: "MobileHeroImage", widget: "image", required: false}
        - label: "Tekstisisältö"
          name: "Markdown"
          widget: object
          fields: 
            - { label: 'Tekstikenttä', name: 'body', widget: 'markdown', required: false, hint: "Tällä palstalla esitettävien kuvien leveys on suurimmillaan **335x**. Sisällön sekaan upotettavat suuret kuvat on suositeltavaa pienentää kyseiseen leveyteen."  }
        - label: "Sivuston metatiedot"
          name: "meta"
          collapsed: false
          hint: "Metatiedot antavat lisää tietoa kyseisestä sivusta. Esimerkiksi Googlen hakutuloksissa tai SoMe jaoissa. Huom! Kuvaus saa olla maksimissaan 150-160 kirjainta pitkä!"
          widget: object
          fields:
          - { label: "Sivun otsikko", name: "title", widget: "string", required: false}
          - { label: "Sivun kuvaus", name: "description", widget: "string", required: false}
          - { label: "Sivun linkki", name: "url", widget: "string", required: false}
          - { label: "Sivun kuva", name: "image", widget: "image", required: false}
    - label: "Pyörät"
      name: "polkupyorat"
      file: "content/sales.json"
      preview_path: polkupyorat
      fields:
        - label: 'Teksti- ja kuvaosio'
          name: "TextImageSection"
          hint: "Laita otsikko, kuvaus ja kuva. Kuvan suositeltu koko olisi 720px leveä ja 500px korkea."
          widget: object
          fields:
          - label: "Kuva ja teksti"
            name: "blocks"
            widget: list
            fields:
              - { label: "Otsikko", name: "title", widget: "string", required: false}
              - { label: "Kuvaus", name: "description", widget: "text", required: false}
              - { label: "Kuva", name: "image", widget: "image", required: false }
        - label: "Hyödyt"
          name: "BenefitsSection"
          widget: object
          fields:
          - { label: "Osion otsikko", name: "SectionTitle", widget: "string", required: false}  
          - label: "Hyödyt"
            name: "benefits"
            hint: "Kuvan suositeltu koko on 115x115 pikseliä."
            widget: list
            max: 3
            allow_add: false
            fields:
              - { label: "Otsikko", name: "title", widget: "string", required: false}
              - { label: "Arvolupaus", name: "valueProposition", widget: "text", required: false}
              - { label: "Kuva", name: "image", widget: "image", required: false }
        - label: "Vapaa tekstikenttä"
          name: "textSection"
          widget: object
          fields: 
            - { label: 'Tekstikenttä', name: 'body', widget: 'markdown', required: false, hint: "Tällä palstalla esitettävien kuvien leveys on suurimmillaan **335x**. Sisällön sekaan upotettavat suuret kuvat on suositeltavaa pienentää kyseiseen leveyteen."  }
        - label: "Nosto"
          name: "highlightSection"
          widget: object
          fields:
            - { label: "Lainaus", name: "quote", widget: "text", required: false}
            - { label: "Siteeraja", name: "quotee", widget: "string", required: false}
            - { label: "Kuva", name: "image", widget: "image", required: false, hint: "Kuvan suositeltu koko on 1280px. Yritä löytää jokin kuva, joka kohdistuu keskelle niin se näyttää hyvältä myös mobiilissa." }
        - label: "Sivuston metatiedot"
          name: "meta"
          collapsed: false
          hint: "Metatiedot antavat lisää tietoa kyseisestä sivusta. Esimerkiksi Googlen hakutuloksissa tai SoMe jaoissa. Huom! Kuvaus saa olla maksimissaan 150-160 kirjainta pitkä!"
          widget: object
          fields:
          - { label: "Sivun otsikko", name: "title", widget: "string", required: false}
          - { label: "Sivun kuvaus", name: "description", widget: "string", required: false}
          - { label: "Sivun linkki", name: "url", widget: "string", required: false}
          - { label: "Sivun kuva", name: "image", widget: "image", required: false}
    - label: "Pyörähuolto"
      name: "pyorahuolto"
      file: "content/repair.json"
      preview_path: pyorahuolto
      fields:
        - label: "Herokuva"
          hint: "Herokuva koostuu kuvasta, otsikosta, tekstistä ja toimintakehotteesta. Suosittelen erikseen laittamaan pöytäkoneelle ja mobiilille omat kuvat. Pöytäkoneen herokuvan speksit on suositeltavaa olla 720x1280 ja mobiilin 1000x1000."
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string", required: false}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "image", required: false}
            - { label: "Mobiilin Herokuva", name: "MobileHeroImage", widget: "image", required: false}
        - label: "Pyörähuollon esite"
          name: "Services"
          widget: object
          fields: 
            - label: "Palvelu ja hinta"
              name: "lists"
              widget: list
              hint: "Laita vain numeraalinen arvo hintaan. Valuutta tulee automaattisesti hinnan perään sivussa."
              fields:
                - { label: "Otsikko", name: "title", widget: "text", required: false}
                - { label: "hinta", name: "price", widget: "string", required: false}
            - { label: 'Tekstikenttä', name: 'body', widget: 'markdown', required: false, hint: "Tällä palstalla esitettävien kuvien leveys on suurimmillaan **335x**. Sisällön sekaan upotettavat suuret kuvat on suositeltavaa pienentää kyseiseen leveyteen."  }
        - label: "Sivuston metatiedot"
          name: "meta"
          collapsed: false
          hint: "Metatiedot antavat lisää tietoa kyseisestä sivusta. Esimerkiksi Googlen hakutuloksissa tai SoMe jaoissa. Huom! Kuvaus saa olla maksimissaan 150-160 kirjainta pitkä!"
          widget: object
          fields:
          - { label: "Sivun otsikko", name: "title", widget: "string", required: false}
          - { label: "Sivun kuvaus", name: "description", widget: "string", required: false}
          - { label: "Sivun linkki", name: "url", widget: "string", required: false}
          - { label: "Sivun kuva", name: "image", widget: "image", required: false}
    - label: "Uutiset"
      name: "news"
      file: "content/news.json"
      preview_path: uutiset
      fields:  
        - label: "Herokuva"
          hint: "Herokuva koostuu kuvasta, otsikosta, tekstistä ja toimintakehotteesta. Suosittelen erikseen laittamaan pöytäkoneelle ja mobiilille omat kuvat. Pöytäkoneen herokuvan speksit on suositeltavaa olla 720x1280 ja mobiilin 1000x1000."
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string", required: false}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "image", required: false}
            - { label: "Mobiilin Herokuva", name: "MobileHeroImage", widget: "image", required: false}      
        - label: 'Uutiset'
          name: "newsSection"
          hint: ""
          widget: object
          fields:
          - { label: "Osion otsikko", name: "SectionTitle", widget: "string", required: false}  
          - label: "Uutinen"
            name: "news"
            add_to_top: true
            widget: list
            fields:
              - { label: "Päiväys", name: "date", widget: "datetime",  date_format: "DD.MM.YYYY", time_format: false, format: "DD.MM.YYYY", required: false}
              - { label: "Otsikko", name: "title", widget: "string", required: false}
              - { label: "Kuvaus", name: "body", widget: "markdown", required: false, hint: "Tällä palstalla esitettävien kuvien leveys on suurimmillaan **335x**. Sisällön sekaan upotettavat suuret kuvat on suositeltavaa pienentää kyseiseen leveyteen." }
              - { label: "Kuva", name: "image", widget: "image", required: false, hint: "Suositeltu kuvakoko on 350x350 pikseliä" }
              - label: "Tiedosto"
                name: "files"
                collapsed: false
                summary: "Lisää tiedosto ja anna sille toimintaa kehoittava otsikko"
                widget: list
                max: 1
                fields:
                  - { label: "Tiedosto", name: "file", widget: "file", allow_multiple: false, required: false }
                  - { label: "Tiedoston otsikko", name: "fileTitle", widget: "string", required: false }
    - label: "Yhteydenotto"
      name: "contact"
      file: "content/contact.json"
      comment: "Aukioloajat sekä yhteystiedot voi muokata Sivuasetuksista."
      hint: "Aukioloajat sekä yhteystiedot voi muokata Sivuasetuksista."
      preview_path: yhteydenotto
      fields:
        - label: "Herokuva"
          hint: "Herokuva koostuu kuvasta, otsikosta, tekstistä ja toimintakehotteesta. Suosittelen erikseen laittamaan pöytäkoneelle ja mobiilille omat kuvat. Pöytäkoneen herokuvan speksit on suositeltavaa olla 720x1280 ja mobiilin 1000x1000."
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string", required: false}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "image", required: false}
            - { label: "Mobiilin Herokuva", name: "MobileHeroImage", widget: "image", required: false}
        - label: "Sivuston metatiedot"
          name: "meta"
          collapsed: false
          hint: "Metatiedot antavat lisää tietoa kyseisestä sivusta. Esimerkiksi Googlen hakutuloksissa tai SoMe jaoissa. Huom! Kuvaus saa olla maksimissaan 150-160 kirjainta pitkä!"
          widget: object
          fields:
          - { label: "Sivun otsikko", name: "title", widget: "string", required: false}
          - { label: "Sivun kuvaus", name: "description", widget: "string", required: false}
          - { label: "Sivun linkki", name: "url", widget: "string", required: false}
          - { label: "Sivun kuva", name: "image", widget: "image", required: false}
    - label: "Työpaikat"
      name: "jobs"
      file: "content/jobs.json"
      preview_path: tyopaikat
      fields:
        - label: "Herokuva"
          hint: "Herokuva koostuu kuvasta, otsikosta, tekstistä ja toimintakehotteesta. Suosittelen erikseen laittamaan pöytäkoneelle ja mobiilille omat kuvat. Pöytäkoneen herokuvan speksit on suositeltavaa olla 720x1280 ja mobiilin 1000x1000."
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string", required: false}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "image", required: false}
            - { label: "Mobiilin Herokuva", name: "MobileHeroImage", widget: "image", required: false}
        - label: "Tekstisisältö"
          name: "Markdown"
          widget: object
          fields: 
            - { label: 'Tekstikenttä', name: 'body', widget: 'markdown', required: false, hint: "Tällä palstalla esitettävien kuvien leveys on suurimmillaan **335x**. Sisällön sekaan upotettavat suuret kuvat on suositeltavaa pienentää kyseiseen leveyteen."  }
        - label: "Sivuston metatiedot"
          name: "meta"
          collapsed: false
          hint: "Metatiedot antavat lisää tietoa kyseisestä sivusta. Esimerkiksi Googlen hakutuloksissa tai SoMe jaoissa. Huom! Kuvaus saa olla maksimissaan 150-160 kirjainta pitkä!"
          widget: object
          fields:
          - { label: "Sivun otsikko", name: "title", widget: "string", required: false}
          - { label: "Sivun kuvaus", name: "description", widget: "string", required: false}
          - { label: "Sivun linkki", name: "url", widget: "string", required: false}
          - { label: "Sivun kuva", name: "image", widget: "image", required: false}
    - label: "Suksihuolto"
      name: "skiis"
      file: "content/skiis.json"
      preview_path: suksihuolto
      fields:
        - label: "Herokuva"
          hint: "Herokuva koostuu kuvasta, otsikosta, tekstistä ja toimintakehotteesta. Suosittelen erikseen laittamaan pöytäkoneelle ja mobiilille omat kuvat. Pöytäkoneen herokuvan speksit on suositeltavaa olla 720x1280 ja mobiilin 1000x1000."
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string", required: false}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "image", required: false}
            - { label: "Mobiilin Herokuva", name: "MobileHeroImage", widget: "image", required: false}
        - label: "Tekstisisältö"
          name: "Markdown"
          widget: object
          fields: 
            - { label: 'Tekstikenttä', name: 'body', widget: 'markdown', required: false }
        - label: "Sivuston metatiedot"
          name: "meta"
          collapsed: false
          hint: "Metatiedot antavat lisää tietoa kyseisestä sivusta. Esimerkiksi Googlen hakutuloksissa tai SoMe jaoissa. Huom! Kuvaus saa olla maksimissaan 150-160 kirjainta pitkä!"
          widget: object
          fields:
          - { label: "Sivun otsikko", name: "title", widget: "string", required: false}
          - { label: "Sivun kuvaus", name: "description", widget: "string", required: false}
          - { label: "Sivun linkki", name: "url", widget: "string", required: false}
          - { label: "Sivun kuva", name: "image", widget: "image", required: false}
    - label: "Talvisäilytys"
      name: "winter"
      file: "content/winter.json"
      preview_path: talvisailytys
      fields:
        - label: "Herokuva"
          hint: "Herokuva koostuu kuvasta, otsikosta, tekstistä ja toimintakehotteesta. Suosittelen erikseen laittamaan pöytäkoneelle ja mobiilille omat kuvat. Pöytäkoneen herokuvan speksit on suositeltavaa olla 720x1280 ja mobiilin 1000x1000."
          name: "Hero"
          widget: object
          fields:
            - { label: "Otsikko", name: "HeroTitle", widget: "string", required: false}
            - { label: "Pöytäkoneen Herokuva", name: "DesktopHeroImage", widget: "image", required: false}
            - { label: "Mobiilin Herokuva", name: "MobileHeroImage", widget: "image", required: false}
        - label: "Tekstisisältö"
          name: "Markdown"
          widget: object
          fields: 
            - { label: 'Tekstikenttä', name: 'body', widget: 'markdown', required: false, hint: "Tällä palstalla esitettävien kuvien leveys on suurimmillaan **335x**. Sisällön sekaan upotettavat suuret kuvat on suositeltavaa pienentää kyseiseen leveyteen."  }
        - label: "Sivuston metatiedot"
          name: "meta"
          collapsed: false
          hint: "Metatiedot antavat lisää tietoa kyseisestä sivusta. Esimerkiksi Googlen hakutuloksissa tai SoMe jaoissa. Huom! Kuvaus saa olla maksimissaan 150-160 kirjainta pitkä!"
          widget: object
          fields:
          - { label: "Sivun otsikko", name: "title", widget: "string", required: false}
          - { label: "Sivun kuvaus", name: "description", widget: "string", required: false}
          - { label: "Sivun linkki", name: "url", widget: "string", required: false}
          - { label: "Sivun kuva", name: "image", widget: "image", required: false}
  - name: "general"
    description: "Sivun yleiset asetukset kuten Ylä- ja alatunniste, yhteystiedot, maksutavat"
    label: "Yleiset asetukset"
    editor:
     preview: false
    files:
    - label: "Sivun asetukset:Ylä- ja alatunniste, yhteystiedot, maksutiedot."
      name: "site"
      file: "content/site.json"
      fields:
        - label: "Logo"
          name: "Logo"
          widget: object
          fields: 
            - { label: "Otsikko", name: "titleLogo", widget: "string", required: false}
            - { label: "Logo", name: "imageLogo", widget: "image", required: false}
            - { label: "Logon täsmennys", name: "imageAlt", widget: "string", required: false}
        - label: "Yhteystiedot"
          name: "Contact"
          widget: object
          max: 4
          delete: false
          allow_add: false
          summary: "Laita tähän haluamasi sähköpostiosoitteet tai puhelinnumerot. Muista merkata puhelinnumerot otsikolle Phone ja sähköpostiosoitteet otsikolla Email"
          fields:
            - { label: "Auki", name: "open", widget: "boolean", required: false,  hint: "Halutaanko alapalkin kenttä automaattisesti auki mobiiliruudussa vai suljettuna"}
            - { label: "Otsikko", name: "title", widget: "string", required: false}
            - { label: "Kuvaus", name: "description", widget: "string", required: false}
            - label: "Yhteystieto"
              name: "contactList"
              widget: list
              fields:
                - { label: "Otsikko", name: "title", widget: "string", required: false}
                - { label: "Yhteystieto", name: "url", widget: "string", required: false}
        - label: "Maksutavat"
          name: "Payment"
          widget: object
          fields:
            - { label: "Auki", name: "open", widget: "boolean", required: false, hint: "Halutaanko alapalkin kenttä automaattisesti auki mobiiliruudussa vai suljettuna"}
            - { label: "Otsikko", name: "title", widget: "string", required: false}
            - { label: "Kuvaus", name: "description", widget: "string", required: false}
            - label: "Maksutapa"
              name: "paymentList"
              widget: list
              fields:
                - { label: "Otsikko", name: "title", widget: "string", required: false}
                - { label: "Kuva", name: "icon", widget: "image", required: false}
        - label: "Liikkeentiedot"
          name: "Company"
          widget: object
          fields: 
            - { label: "Auki", name: "open", widget: "boolean", required: false, hint: "Halutaanko alapalkin kenttä automaattisesti auki mobiiliruudussa vai suljettuna"}
            - { label: "Otsikko", name: "title", widget: "string", required: false}
            - { label: "Osoite", name: "address", widget: "string", required: false}
            - { label: "Postinumero", name: "postalCode", widget: "string", required: false}
            - { label: "Kartta-linkki", name: "mapURL", widget: "string", required: false}
            - { label: "Kartta-otsikko", name: "mapCTATitle", widget: "string", required: false}
            - { label: "Aukiolo otsikko", name: "openingHoursTitle", widget: "string", required: false}
            - { label: "Auki arkena", name: "openingHoursWeekDays", widget: "string", required: false}
            - { label: "Auki viikonloppuna", name: "openingHoursWeekend", widget: "string", required: false}
